return {
    name = "luvit/luvit",
    version = "3.0.0-alpha",
    license = "Apache 2",
    homepage = "https://github.com/luvit/luvit",
    description = "node.js style APIs for luvi as either a luvi app or library.",
    tags = {"luvit", "meta"},
    author = {name = "Tim Caswell"},
    contributors = {
        "Ryan Phillips",
        "George Zhao",
        "Rob Emanuele",
        "Daniel Barney",
        "Ryan Liptak",
        "Kenneth Wilke",
        "Gabriel Nicolas Avellaneda",
    },
    dependencies = {},
    files = {"*.lua"},
}
